language: c
os:
  - linux
compiler:
  - gcc-4.8
env:
  - OPJ_CI_ABI_CHECK=1
  
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-4.8
      - gcc-multilib
      - gcc-mingw-w64-base
      - binutils-mingw-w64-i686
      - binutils-mingw-w64-x86-64
      - gcc-mingw-w64-i686
      - gcc-mingw-w64-x86-64
      - gcc-mingw-w64
      - libelf-dev
      - elfutils
      - texinfo
      - exuberant-ctags

install:
  - ./tools/travis-ci/install.sh

script:
  - ./tools/travis-ci/run.sh
  - ./tools/travis-ci/abi-check.sh
