language: c
before_install:
  - cmake --version
  - git clone --depth=1 --branch=master git://github.com/uclouvain/openjpeg-data.git data
compiler:
  - gcc
script:
    - mkdir build
    - cd build
    - cmake -G "Unix Makefiles" -DBUILD_CODEC=ON -DBUILD_THIRDPARTY=ON -DBUILD_TESTING=ON -DOPJ_DATA_ROOT=../data -DSITE=travis-ci.org ..
    - make
    - ctest -D ExperimentalStart
    - ctest -D ExperimentalTest -j2 || true
    - ctest -D ExperimentalSubmit || true
