language: c
os:
  - linux
  - osx
compiler:
  - gcc
  - clang
env:
  - OPJ_CI_ARCH=x86_64
  - OPJ_CI_ARCH=i386
  - OPJ_CI_BUILD_CONFIGURATION=Release
  - OPJ_CI_BUILD_CONFIGURATION=Debug
  
matrix:
  exclude:
    - os: osx
      compiler: gcc
    - compiler: clang
      env: OPJ_CI_ARCH=i386
    - compiler: gcc
      env: OPJ_CI_BUILD_CONFIGURATION=Debug
    - os: osx
      env: OPJ_CI_BUILD_CONFIGURATION=Debug
  
addons:
  apt:
    packages:
      - gcc-multilib

install:
  - ./tools/travis-ci/install.sh

script:
  - ./tools/travis-ci/run.sh
