language: c
os:
  - linux
#  - osx
compiler:
#  - gcc
#  - clang
  - x86_64-w64-mingw32-gcc
env:
  - OPJ_CI_ARCH=x86_64 OPJ_CI_BUILD_CONFIGURATION=Release
  - OPJ_CI_ARCH=i386 OPJ_CI_BUILD_CONFIGURATION=Release
  - OPJ_CI_ARCH=x86_64 OPJ_CI_BUILD_CONFIGURATION=Debug OPJ_CI_ASAN=1
  
matrix:
  exclude:
    - os: osx
      compiler: gcc
    - os: osx
      compiler: x86_64-w64-mingw32-gcc
    - compiler: clang
      env: OPJ_CI_ARCH=i386 OPJ_CI_BUILD_CONFIGURATION=Release
    - compiler: gcc
      env: OPJ_CI_ARCH=x86_64 OPJ_CI_BUILD_CONFIGURATION=Debug OPJ_CI_ASAN=1
    - compiler: x86_64-w64-mingw32-gcc
      env: OPJ_CI_ARCH=x86_64 OPJ_CI_BUILD_CONFIGURATION=Debug OPJ_CI_ASAN=1
    - os: osx
      env: OPJ_CI_ARCH=x86_64 OPJ_CI_BUILD_CONFIGURATION=Debug OPJ_CI_ASAN=1
  
addons:
  apt:
    packages:
      - gcc-multilib
      - gcc-mingw-w64

install:
  - ./tools/travis-ci/install.sh

script:
  - ./tools/travis-ci/run.sh
