language: c
compiler:
  - gcc

before_install:
  - cmake --version
  - git clone --depth=1 --branch=master git://github.com/uclouvain/openjpeg-data.git data
  - wget -qO - https://github.com/openpreserve/jpylyzer/archive/1.14.2.tar.gz | tar -xzf
install:
  - chmod +x jpylyzer-1.14.2/jpylyzer/jpylyzer.py

script:
    - mkdir build
    - cd build
    - cmake -G "Unix Makefiles" -DCMAKE_BUILD_TYPE=Release -DBUILD_CODEC=ON -DBUILD_THIRDPARTY=ON -DBUILD_TESTING=ON -DOPJ_DATA_ROOT=${PWD}/../data -DJPYLYZER_EXECUTABLE=${PWD}/../jpylyzer-1.14.2/jpylyzer/jpylyzer.py -DSITE=travis-ci.org -DBUILDNAME=${TRAVIS_OS_NAME}-${CC}$(${CC} -dumpversion)-x86_64-${TRAVIS_BRANCH}$( [[ "${TRAVIS_PULL_REQUEST}" != "false" ]] && echo "-pr${TRAVIS_PULL_REQUEST}" )-Release-3rdP ..
    - ctest -D ExperimentalStart
    - ctest -D ExperimentalBuild -V
    - ctest -D ExperimentalTest -j2 || true
    - ctest -D ExperimentalSubmit || true
